# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "AlmondWhite" 

# A description of your site for social meta tag, search engines, and feed.xml
description: "A blog on all things interesting..."

# Tagline near the site title
tagline: "A blog on all things interesting..."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://almondwhite.today"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "AlmondWhite"
author_bio: "I'm a coder, artist, writer and all round lazy person. I love Node.js, C#, Python, Sass, Electron and PHP. One day I will contribute to this world in a meningful way or something..."
author_url:  "https://medium.com/@almondwhite"
author_location: "The Forest Somewhere"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "https://almondwhite.today"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: ""

# Social links in the site footer
twitter_username: "AImondWhite"
facebook_username: ""
googleplus_username: ""
github_username: "AlmondWhite"
codepen_username: ""
dribbble_uername: ""
medium_username: ""
instagram_username: ""
pinterest_username: ""
linkedin_username: "@almondwhite"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
